---
openapi: 3.0.0
info:
   version: 1.3.0
   title: cheiconstru open api specification
   description: attendancerecord API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8042
     description: attendancerecord
tags:
- name: attendancerecord
paths:
   "/attendancerecord/{id}":
      delete:
         tags:
         -  attendancerecord
         description: GpDelete
         parameters:
         -  in: "path"
            description: GpDelete
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  attendancerecord
         description: GpGetEntityById
         parameters:
         -  in: "path"
            description: GpGetEntityById
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/attendancerecord/get/search":
      get:
         tags:
         -  attendancerecord
         description: GpSearch
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/attendancerecord/get/update":
      put:
         tags:
         -  attendancerecord
         description: GpSearchForUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/attendancerecord"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/attendancerecord":
      put:
         tags:
         -  attendancerecord
         description: GpUpdate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/attendancerecord"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      get:
         tags:
         -  attendancerecord
         description: GpGetAllValues
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
      post:
         tags:
         -  attendancerecord
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/attendancerecord"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/attendancerecord/userid/created_by":
      get:
         tags:
         -  attendancerecord
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      attendancerecord:
         type: object
         properties:
            name:
               type: "string"
               description: Description
            access_profile:
               type: "string"
               description: Description
            attendancedate:
               type: "string"
               description: Description
            attendance:
               type: "string"
               description: Description
            inTime:
               type: "string"
               description: Description
            outTime:
               type: "string"
               description: Description
            fromDate:
               type: "string"
               description: Description
            toDate:
               type: "string"
               description: Description